services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env  # Explicitly reference the root .env file
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
