version: "3.8"

services:
  backend:
    build:
      context: ./backend  # Ensures Docker looks inside backend/
    ports:
      - "8000:8000"
    env_file:
      - .env  # Ensure .env is correctly loaded
    depends_on:
      - mongo
    volumes:
      - ./backend:/app

  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
